# Generated by Django 2.2 on 2019-12-11 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Juego',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_ficha', models.PositiveIntegerField()),
                ('nombre_juego', models.CharField(max_length=35)),
            ],
        ),
        migrations.CreateModel(
            name='tipoApuesta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('pagoPorFicha', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Apuesta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_apostada', models.PositiveIntegerField()),
                ('created_at', models.DateField(auto_now_add=True)),
                ('resultado_1', models.PositiveIntegerField(null=True)),
                ('resultado_2', models.PositiveIntegerField(null=True)),
                ('resultado_apuesta', models.IntegerField(null=True)),
                ('juego', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apuestas.Juego')),
            ],
        ),
    ]
