# Generated by Django 2.2 on 2019-11-14 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tipoApuesta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('pagoPorFicha', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Apuesta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_1', models.CharField(max_length=200)),
                ('team_2', models.CharField(max_length=200)),
                ('date', models.DateField(auto_now_add=True)),
                ('apuesta', models.IntegerField()),
                ('tipo_apuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apuestas.tipoApuesta')),
            ],
        ),
    ]
