# Generated by Django 2.2 on 2019-12-08 03:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Juego',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_ficha', models.PositiveIntegerField()),
                ('nombre_juego', models.CharField(max_length=35)),
            ],
        ),
        migrations.CreateModel(
            name='tipoApuesta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('pagoPorFicha', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Apuesta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_apostada', models.PositiveIntegerField()),
                ('fecha', models.DateField()),
                ('resultado_descanzo', models.PositiveIntegerField(verbose_name='resultado_descanzo')),
                ('resultado_final', models.PositiveIntegerField(verbose_name='resultado_final')),
                ('resultado_local', models.PositiveIntegerField(verbose_name='resultado_local')),
                ('resultado_visitante', models.PositiveIntegerField(verbose_name='resultado_vistante')),
                ('juego', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='apuestas.Juego')),
            ],
        ),
    ]
