# Generated by Django 2.2 on 2019-12-08 04:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apuestas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apuesta',
            name='juego',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apuestas.Juego'),
        ),
    ]
