# Generated by Django 2.2 on 2019-12-11 22:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('apuestas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loteria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activa', models.BooleanField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ResultadoLoteria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resultado_total', models.PositiveIntegerField()),
                ('id_partido', models.PositiveIntegerField()),
                ('estado_resultado', models.CharField(choices=[('PERDIO', 'PERDIO'), ('GANO', 'GANO'), ('PENDIENTE', 'PENDIENTE')], max_length=9)),
                ('loteria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apuestas.Loteria')),
            ],
        ),
    ]
