# Generated by Django 2.2 on 2019-12-09 22:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('apuestas', '0002_auto_20191208_0437'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apuesta',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='apuesta',
            name='resultado_descanzo',
        ),
        migrations.RemoveField(
            model_name='apuesta',
            name='resultado_final',
        ),
        migrations.RemoveField(
            model_name='apuesta',
            name='resultado_local',
        ),
        migrations.RemoveField(
            model_name='apuesta',
            name='resultado_visitante',
        ),
        migrations.AddField(
            model_name='apuesta',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='apuesta',
            name='resultado_1',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='apuesta',
            name='resultado_2',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='apuesta',
            name='resultado_apuesta',
            field=models.IntegerField(null=True),
        ),
    ]
